# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'ferias',
            },
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='id_funcionario',
            new_name='id',
        ),
        migrations.AddField(
            model_name='ferias',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RHIN.Funcionario'),
        ),
    ]
