# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0003_auto_20170405_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='flg_type',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='ferias',
            table='afastamento',
        ),
    ]
