# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0004_auto_20170405_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferias',
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='Ferias',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
