# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RHIN', '0005_auto_20170415_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
                ('flg_type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'afastamento',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('cep', models.CharField(default='', max_length=9)),
                ('address', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=30)),
                ('phone1', models.CharField(default='', max_length=15)),
                ('phone2', models.CharField(default='', max_length=15)),
                ('born_date', models.DateField(default=None)),
                ('gender', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.AddField(
            model_name='ferias',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RHIN.Funcionario'),
        ),
    ]
