# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0007_auto_20170415_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=50)),
                ('is_active', models.IntegerField(default=1)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RHIN.Funcionario')),
            ],
        ),
    ]
