# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0008_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
