# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0009_auto_20170415_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(default='', max_length=30),
        ),
    ]
