# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0011_auto_20170426_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('dia', models.IntegerField(default=0)),
                ('inicio1', models.TimeField(default=None)),
                ('fim1', models.TimeField(default=None)),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RHIN.Cargo')),
            ],
        ),
    ]
