# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0014_auto_20170428_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio1', models.TimeField(default=None)),
                ('fim1', models.TimeField(default=None)),
                ('inicio2', models.TimeField(default=None)),
                ('fim2', models.TimeField(default=None)),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RHIN.Cargo')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
    ]
