# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0016_auto_20170428_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio1', models.TimeField(default=None)),
                ('fim1', models.TimeField(default=None)),
                ('inicio2', models.TimeField(default=None)),
                ('fim2', models.TimeField(default=None)),
            ],
            options={
                'db_table': 'dia_horario',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_turno', models.CharField(default='', max_length=120)),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RHIN.Cargo')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.AddField(
            model_name='diahorario',
            name='horario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RHIN.Horario'),
        ),
    ]
