# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0018_remove_horario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='cargo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='RHIN.Cargo'),
            preserve_default=False,
        ),
    ]
