# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0019_horario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diahorario',
            name='dia',
            field=models.IntegerField(default=None),
        ),
    ]
