# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0020_diahorario_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diahorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RHIN.Horario'),
        ),
    ]
