# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0023_remove_user_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.FloatField(default=None),
        ),
    ]
