# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHIN', '0025_remove_horario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='phone1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='phone2',
            field=models.CharField(default='', max_length=30),
        ),
    ]
